// Mock data for development

import type { Surah, Juz, QuranVerse, Hadith, Article, Dua, Adhkar, Book } from "./types"

export const mockSurahs: Surah[] = [
  { id: 1,  name: "Al-Fatihah",      arabicName: "الفاتحة",    numberOfVerses: 7,   revelationType: "Makki",  juzStart: 1 },
  { id: 2,  name: "Al-Baqarah",      arabicName: "البقرة",     numberOfVerses: 286, revelationType: "Madani", juzStart: 1 },
  { id: 3,  name: "Ali 'Imran",      arabicName: "آل عمران",   numberOfVerses: 200, revelationType: "Madani", juzStart: 3 },
  { id: 4,  name: "An-Nisa",         arabicName: "النساء",     numberOfVerses: 176, revelationType: "Madani", juzStart: 4 },
  { id: 5,  name: "Al-Ma'idah",      arabicName: "المائدة",    numberOfVerses: 120, revelationType: "Madani", juzStart: 6 },
  { id: 6,  name: "Al-An'am",        arabicName: "الأنعام",    numberOfVerses: 165, revelationType: "Makki",  juzStart: 7 },
  { id: 7,  name: "Al-A'raf",        arabicName: "الأعراف",    numberOfVerses: 206, revelationType: "Makki",  juzStart: 8 },
  { id: 8,  name: "Al-Anfal",        arabicName: "الأنفال",    numberOfVerses: 75,  revelationType: "Madani", juzStart: 9 },
  { id: 9,  name: "At-Tawbah",       arabicName: "التوبة",     numberOfVerses: 129, revelationType: "Madani", juzStart: 10 },
  { id: 10, name: "Yunus",           arabicName: "يونس",       numberOfVerses: 109, revelationType: "Makki",  juzStart: 11 },
  { id: 11, name: "Hud",             arabicName: "هود",        numberOfVerses: 123, revelationType: "Makki",  juzStart: 11 },
  { id: 12, name: "Yusuf",           arabicName: "يوسف",       numberOfVerses: 111, revelationType: "Makki",  juzStart: 12 },
  { id: 13, name: "Ar-Ra'd",         arabicName: "الرعد",      numberOfVerses: 43,  revelationType: "Madani", juzStart: 13 },
  { id: 14, name: "Ibrahim",         arabicName: "إبراهيم",    numberOfVerses: 52,  revelationType: "Makki",  juzStart: 13 },
  { id: 15, name: "Al-Hijr",         arabicName: "الحجر",      numberOfVerses: 99,  revelationType: "Makki",  juzStart: 14 },
  { id: 16, name: "An-Nahl",         arabicName: "النحل",      numberOfVerses: 128, revelationType: "Makki",  juzStart: 14 },
  { id: 17, name: "Al-Isra",         arabicName: "الإسراء",    numberOfVerses: 111, revelationType: "Makki",  juzStart: 15 },
  { id: 18, name: "Al-Kahf",         arabicName: "الكهف",      numberOfVerses: 110, revelationType: "Makki",  juzStart: 15 },
  { id: 19, name: "Maryam",          arabicName: "مريم",       numberOfVerses: 98,  revelationType: "Makki",  juzStart: 16 },
  { id: 20, name: "Ta-Ha",           arabicName: "طه",         numberOfVerses: 135, revelationType: "Makki",  juzStart: 16 },
  { id: 21, name: "Al-Anbiya",       arabicName: "الأنبياء",   numberOfVerses: 112, revelationType: "Makki",  juzStart: 17 },
  { id: 22, name: "Al-Hajj",         arabicName: "الحج",       numberOfVerses: 78,  revelationType: "Madani", juzStart: 17 },
  { id: 23, name: "Al-Mu'minun",     arabicName: "المؤمنون",   numberOfVerses: 118, revelationType: "Makki",  juzStart: 18 },
  { id: 24, name: "An-Nur",          arabicName: "النور",      numberOfVerses: 64,  revelationType: "Madani", juzStart: 18 },
  { id: 25, name: "Al-Furqan",       arabicName: "الفرقان",    numberOfVerses: 77,  revelationType: "Makki",  juzStart: 18 },
  { id: 26, name: "Ash-Shu'ara",     arabicName: "الشعراء",    numberOfVerses: 227, revelationType: "Makki",  juzStart: 19 },
  { id: 27, name: "An-Naml",         arabicName: "النمل",      numberOfVerses: 93,  revelationType: "Makki",  juzStart: 19 },
  { id: 28, name: "Al-Qasas",        arabicName: "القصص",      numberOfVerses: 88,  revelationType: "Makki",  juzStart: 20 },
  { id: 29, name: "Al-'Ankabut",     arabicName: "العنكبوت",   numberOfVerses: 69,  revelationType: "Makki",  juzStart: 20 },
  { id: 30, name: "Ar-Rum",          arabicName: "الروم",      numberOfVerses: 60,  revelationType: "Makki",  juzStart: 21 },
  { id: 31, name: "Luqman",          arabicName: "لقمان",      numberOfVerses: 34,  revelationType: "Makki",  juzStart: 21 },
  { id: 32, name: "As-Sajdah",       arabicName: "السجدة",     numberOfVerses: 30,  revelationType: "Makki",  juzStart: 21 },
  { id: 33, name: "Al-Ahzab",        arabicName: "الأحزاب",    numberOfVerses: 73,  revelationType: "Madani", juzStart: 21 },
  { id: 34, name: "Saba",            arabicName: "سبأ",        numberOfVerses: 54,  revelationType: "Makki",  juzStart: 22 },
  { id: 35, name: "Fatir",           arabicName: "فاطر",       numberOfVerses: 45,  revelationType: "Makki",  juzStart: 22 },
  { id: 36, name: "Ya-Sin",          arabicName: "يس",         numberOfVerses: 83,  revelationType: "Makki",  juzStart: 22 },
  { id: 37, name: "As-Saffat",       arabicName: "الصافات",    numberOfVerses: 182, revelationType: "Makki",  juzStart: 23 },
  { id: 38, name: "Sad",             arabicName: "ص",          numberOfVerses: 88,  revelationType: "Makki",  juzStart: 23 },
  { id: 39, name: "Az-Zumar",        arabicName: "الزمر",      numberOfVerses: 75,  revelationType: "Makki",  juzStart: 23 },
  { id: 40, name: "Ghafir",          arabicName: "غافر",       numberOfVerses: 85,  revelationType: "Makki",  juzStart: 24 },
  { id: 41, name: "Fussilat",        arabicName: "فصلت",       numberOfVerses: 54,  revelationType: "Makki",  juzStart: 24 },
  { id: 42, name: "Ash-Shura",       arabicName: "الشورى",     numberOfVerses: 53,  revelationType: "Makki",  juzStart: 25 },
  { id: 43, name: "Az-Zukhruf",      arabicName: "الزخرف",     numberOfVerses: 89,  revelationType: "Makki",  juzStart: 25 },
  { id: 44, name: "Ad-Dukhan",       arabicName: "الدخان",     numberOfVerses: 59,  revelationType: "Makki",  juzStart: 25 },
  { id: 45, name: "Al-Jathiyah",     arabicName: "الجاثية",    numberOfVerses: 37,  revelationType: "Makki",  juzStart: 25 },
  { id: 46, name: "Al-Ahqaf",        arabicName: "الأحقاف",    numberOfVerses: 35,  revelationType: "Makki",  juzStart: 26 },
  { id: 47, name: "Muhammad",        arabicName: "محمد",       numberOfVerses: 38,  revelationType: "Madani", juzStart: 26 },
  { id: 48, name: "Al-Fath",         arabicName: "الفتح",      numberOfVerses: 29,  revelationType: "Madani", juzStart: 26 },
  { id: 49, name: "Al-Hujurat",      arabicName: "الحجرات",    numberOfVerses: 18,  revelationType: "Madani", juzStart: 26 },
  { id: 50, name: "Qaf",             arabicName: "ق",          numberOfVerses: 45,  revelationType: "Makki",  juzStart: 26 },
  { id: 51, name: "Adh-Dhariyat",    arabicName: "الذاريات",   numberOfVerses: 60,  revelationType: "Makki",  juzStart: 26 },
  { id: 52, name: "At-Tur",          arabicName: "الطور",      numberOfVerses: 49,  revelationType: "Makki",  juzStart: 27 },
  { id: 53, name: "An-Najm",         arabicName: "النجم",      numberOfVerses: 62,  revelationType: "Makki",  juzStart: 27 },
  { id: 54, name: "Al-Qamar",        arabicName: "القمر",      numberOfVerses: 55,  revelationType: "Makki",  juzStart: 27 },
  { id: 55, name: "Ar-Rahman",       arabicName: "الرحمن",     numberOfVerses: 78,  revelationType: "Madani", juzStart: 27 },
  { id: 56, name: "Al-Waqi'ah",      arabicName: "الواقعة",    numberOfVerses: 96,  revelationType: "Makki",  juzStart: 27 },
  { id: 57, name: "Al-Hadid",        arabicName: "الحديد",     numberOfVerses: 29,  revelationType: "Madani", juzStart: 27 },
  { id: 58, name: "Al-Mujadila",     arabicName: "المجادلة",   numberOfVerses: 22,  revelationType: "Madani", juzStart: 28 },
  { id: 59, name: "Al-Hashr",        arabicName: "الحشر",      numberOfVerses: 24,  revelationType: "Madani", juzStart: 28 },
  { id: 60, name: "Al-Mumtahanah",   arabicName: "الممتحنة",   numberOfVerses: 13,  revelationType: "Madani", juzStart: 28 },
  { id: 61, name: "As-Saf",          arabicName: "الصف",       numberOfVerses: 14,  revelationType: "Madani", juzStart: 28 },
  { id: 62, name: "Al-Jumu'ah",      arabicName: "الجمعة",     numberOfVerses: 11,  revelationType: "Madani", juzStart: 28 },
  { id: 63, name: "Al-Munafiqun",    arabicName: "المنافقون",  numberOfVerses: 11,  revelationType: "Madani", juzStart: 28 },
  { id: 64, name: "At-Taghabun",     arabicName: "التغابن",    numberOfVerses: 18,  revelationType: "Madani", juzStart: 28 },
  { id: 65, name: "At-Talaq",        arabicName: "الطلاق",     numberOfVerses: 12,  revelationType: "Madani", juzStart: 28 },
  { id: 66, name: "At-Tahrim",       arabicName: "التحريم",    numberOfVerses: 12,  revelationType: "Madani", juzStart: 28 },
  { id: 67, name: "Al-Mulk",         arabicName: "الملك",      numberOfVerses: 30,  revelationType: "Makki",  juzStart: 29 },
  { id: 68, name: "Al-Qalam",        arabicName: "القلم",      numberOfVerses: 52,  revelationType: "Makki",  juzStart: 29 },
  { id: 69, name: "Al-Haqqah",       arabicName: "الحاقة",     numberOfVerses: 52,  revelationType: "Makki",  juzStart: 29 },
  { id: 70, name: "Al-Ma'arij",      arabicName: "المعارج",    numberOfVerses: 44,  revelationType: "Makki",  juzStart: 29 },
  { id: 71, name: "Nuh",             arabicName: "نوح",        numberOfVerses: 28,  revelationType: "Makki",  juzStart: 29 },
  { id: 72, name: "Al-Jinn",         arabicName: "الجن",       numberOfVerses: 28,  revelationType: "Makki",  juzStart: 29 },
  { id: 73, name: "Al-Muzzammil",    arabicName: "المزمل",     numberOfVerses: 20,  revelationType: "Makki",  juzStart: 29 },
  { id: 74, name: "Al-Muddathir",    arabicName: "المدثر",     numberOfVerses: 56,  revelationType: "Makki",  juzStart: 29 },
  { id: 75, name: "Al-Qiyamah",      arabicName: "القيامة",    numberOfVerses: 40,  revelationType: "Makki",  juzStart: 29 },
  { id: 76, name: "Al-Insan",        arabicName: "الإنسان",    numberOfVerses: 31,  revelationType: "Madani", juzStart: 29 },
  { id: 77, name: "Al-Mursalat",     arabicName: "المرسلات",   numberOfVerses: 50,  revelationType: "Makki",  juzStart: 29 },
  { id: 78, name: "An-Naba",         arabicName: "النبأ",      numberOfVerses: 40,  revelationType: "Makki",  juzStart: 30 },
  { id: 79, name: "An-Nazi'at",      arabicName: "النازعات",   numberOfVerses: 46,  revelationType: "Makki",  juzStart: 30 },
  { id: 80, name: "'Abasa",          arabicName: "عبس",        numberOfVerses: 42,  revelationType: "Makki",  juzStart: 30 },
  { id: 81, name: "At-Takwir",       arabicName: "التكوير",    numberOfVerses: 29,  revelationType: "Makki",  juzStart: 30 },
  { id: 82, name: "Al-Infitar",      arabicName: "الانفطار",   numberOfVerses: 19,  revelationType: "Makki",  juzStart: 30 },
  { id: 83, name: "Al-Mutaffifin",   arabicName: "المطففين",   numberOfVerses: 36,  revelationType: "Makki",  juzStart: 30 },
  { id: 84, name: "Al-Inshiqaq",     arabicName: "الانشقاق",   numberOfVerses: 25,  revelationType: "Makki",  juzStart: 30 },
  { id: 85, name: "Al-Buruj",        arabicName: "البروج",     numberOfVerses: 22,  revelationType: "Makki",  juzStart: 30 },
  { id: 86, name: "At-Tariq",        arabicName: "الطارق",     numberOfVerses: 17,  revelationType: "Makki",  juzStart: 30 },
  { id: 87, name: "Al-A'la",         arabicName: "الأعلى",     numberOfVerses: 19,  revelationType: "Makki",  juzStart: 30 },
  { id: 88, name: "Al-Ghashiyah",    arabicName: "الغاشية",    numberOfVerses: 26,  revelationType: "Makki",  juzStart: 30 },
  { id: 89, name: "Al-Fajr",         arabicName: "الفجر",      numberOfVerses: 30,  revelationType: "Makki",  juzStart: 30 },
  { id: 90, name: "Al-Balad",        arabicName: "البلد",      numberOfVerses: 20,  revelationType: "Makki",  juzStart: 30 },
  { id: 91, name: "Ash-Shams",       arabicName: "الشمس",      numberOfVerses: 15,  revelationType: "Makki",  juzStart: 30 },
  { id: 92, name: "Al-Layl",         arabicName: "الليل",      numberOfVerses: 21,  revelationType: "Makki",  juzStart: 30 },
  { id: 93, name: "Ad-Duha",         arabicName: "الضحى",      numberOfVerses: 11,  revelationType: "Makki",  juzStart: 30 },
  { id: 94, name: "Ash-Sharh",       arabicName: "الشرح",      numberOfVerses: 8,   revelationType: "Makki",  juzStart: 30 },
  { id: 95, name: "At-Tin",          arabicName: "التين",      numberOfVerses: 8,   revelationType: "Makki",  juzStart: 30 },
  { id: 96, name: "Al-'Alaq",        arabicName: "العلق",      numberOfVerses: 19,  revelationType: "Makki",  juzStart: 30 },
  { id: 97, name: "Al-Qadr",         arabicName: "القدر",      numberOfVerses: 5,   revelationType: "Makki",  juzStart: 30 },
  { id: 98, name: "Al-Bayyinah",     arabicName: "البينة",     numberOfVerses: 8,   revelationType: "Madani", juzStart: 30 },
  { id: 99, name: "Az-Zalzalah",     arabicName: "الزلزلة",    numberOfVerses: 8,   revelationType: "Madani", juzStart: 30 },
  { id: 100, name: "Al-'Adiyat",     arabicName: "العاديات",   numberOfVerses: 11,  revelationType: "Makki",  juzStart: 30 },
  { id: 101, name: "Al-Qari'ah",     arabicName: "القارعة",    numberOfVerses: 11,  revelationType: "Makki",  juzStart: 30 },
  { id: 102, name: "At-Takathur",    arabicName: "التكاثر",    numberOfVerses: 8,   revelationType: "Makki",  juzStart: 30 },
  { id: 103, name: "Al-'Asr",        arabicName: "العصر",      numberOfVerses: 3,   revelationType: "Makki",  juzStart: 30 },
  { id: 104, name: "Al-Humazah",     arabicName: "الهمزة",     numberOfVerses: 9,   revelationType: "Makki",  juzStart: 30 },
  { id: 105, name: "Al-Fil",         arabicName: "الفيل",      numberOfVerses: 5,   revelationType: "Makki",  juzStart: 30 },
  { id: 106, name: "Quraysh",        arabicName: "قريش",       numberOfVerses: 4,   revelationType: "Makki",  juzStart: 30 },
  { id: 107, name: "Al-Ma'un",       arabicName: "الماعون",    numberOfVerses: 7,   revelationType: "Makki",  juzStart: 30 },
  { id: 108, name: "Al-Kawthar",     arabicName: "الكوثر",     numberOfVerses: 3,   revelationType: "Makki",  juzStart: 30 },
  { id: 109, name: "Al-Kafirun",     arabicName: "الكافرون",   numberOfVerses: 6,   revelationType: "Makki",  juzStart: 30 },
  { id: 110, name: "An-Nasr",        arabicName: "النصر",      numberOfVerses: 3,   revelationType: "Madani", juzStart: 30 },
  { id: 111, name: "Al-Masad",       arabicName: "المسد",      numberOfVerses: 5,   revelationType: "Makki",  juzStart: 30 },
  { id: 112, name: "Al-Ikhlas",      arabicName: "الإخلاص",    numberOfVerses: 4,   revelationType: "Makki",  juzStart: 30 },
  { id: 113, name: "Al-Falaq",       arabicName: "الفلق",      numberOfVerses: 5,   revelationType: "Makki",  juzStart: 30 },
  { id: 114, name: "An-Nas",         arabicName: "الناس",      numberOfVerses: 6,   revelationType: "Makki",  juzStart: 30 },
]

export const mockJuzList: Juz[] = [
  { number: 1,  arabicName: "الم",               startSurah: 1,   startVerse: 1,  endSurah: 2,   endVerse: 141, totalVerses: 148 },
  { number: 2,  arabicName: "سَيَقُولُ",          startSurah: 2,   startVerse: 142, endSurah: 2,   endVerse: 252, totalVerses: 111 },
  { number: 3,  arabicName: "تِلْكَ الرُّسُلُ",   startSurah: 2,   startVerse: 253, endSurah: 3,   endVerse: 92,  totalVerses: 126 },
  { number: 4,  arabicName: "لَنْ تَنَالُوا",     startSurah: 3,   startVerse: 93,  endSurah: 4,   endVerse: 23,  totalVerses: 129 },
  { number: 5,  arabicName: "وَالْمُحْصَنَاتُ",   startSurah: 4,   startVerse: 24,  endSurah: 4,   endVerse: 147, totalVerses: 124 },
  { number: 6,  arabicName: "لَا يُحِبُّ اللَّهُ", startSurah: 4,   startVerse: 148, endSurah: 5,   endVerse: 81,  totalVerses: 111 },
  { number: 7,  arabicName: "وَإِذَا سَمِعُوا",   startSurah: 5,   startVerse: 82,  endSurah: 6,   endVerse: 110, totalVerses: 149 },
  { number: 8,  arabicName: "وَلَوْ أَنَّنَا",    startSurah: 6,   startVerse: 111, endSurah: 7,   endVerse: 87,  totalVerses: 142 },
  { number: 9,  arabicName: "قَالَ الْمَلَأُ",    startSurah: 7,   startVerse: 88,  endSurah: 8,   endVerse: 40,  totalVerses: 159 },
  { number: 10, arabicName: "وَاعْلَمُوا",        startSurah: 8,   startVerse: 41,  endSurah: 9,   endVerse: 92,  totalVerses: 129 },
  { number: 11, arabicName: "يَعْتَذِرُونَ",      startSurah: 9,   startVerse: 93,  endSurah: 11,  endVerse: 5,   totalVerses: 148 },
  { number: 12, arabicName: "وَمَا مِنْ دَابَّةٍ", startSurah: 11,  startVerse: 6,   endSurah: 12,  endVerse: 52,  totalVerses: 170 },
  { number: 13, arabicName: "وَمَا أُبَرِّئُ",    startSurah: 12,  startVerse: 53,  endSurah: 14,  endVerse: 52,  totalVerses: 154 },
  { number: 14, arabicName: "رُبَمَا",            startSurah: 15,  startVerse: 1,   endSurah: 16,  endVerse: 128, totalVerses: 227 },
  { number: 15, arabicName: "سُبْحَانَ الَّذِي",  startSurah: 17,  startVerse: 1,   endSurah: 18,  endVerse: 74,  totalVerses: 185 },
  { number: 16, arabicName: "قَالَ أَلَمْ",       startSurah: 18,  startVerse: 75,  endSurah: 20,  endVerse: 135, totalVerses: 233 },
  { number: 17, arabicName: "اقْتَرَبَ",          startSurah: 21,  startVerse: 1,   endSurah: 22,  endVerse: 78,  totalVerses: 190 },
  { number: 18, arabicName: "قَدْ أَفْلَحَ",      startSurah: 23,  startVerse: 1,   endSurah: 25,  endVerse: 20,  totalVerses: 202 },
  { number: 19, arabicName: "وَقَالَ الَّذِينَ",  startSurah: 25,  startVerse: 21,  endSurah: 27,  endVerse: 55,  totalVerses: 299 },
  { number: 20, arabicName: "أَمَّنْ خَلَقَ",     startSurah: 27,  startVerse: 56,  endSurah: 29,  endVerse: 45,  totalVerses: 181 },
  { number: 21, arabicName: "اتْلُ مَا أُوحِيَ", startSurah: 29,  startVerse: 46,  endSurah: 33,  endVerse: 30,  totalVerses: 179 },
  { number: 22, arabicName: "وَمَنْ يَقْنُتْ",   startSurah: 33,  startVerse: 31,  endSurah: 36,  endVerse: 27,  totalVerses: 169 },
  { number: 23, arabicName: "وَمَا لِيَ",         startSurah: 36,  startVerse: 28,  endSurah: 39,  endVerse: 31,  totalVerses: 357 },
  { number: 24, arabicName: "فَمَنْ أَظْلَمُ",   startSurah: 39,  startVerse: 32,  endSurah: 41,  endVerse: 46,  totalVerses: 246 },
  { number: 25, arabicName: "إِلَيْهِ يُرَدُّ",  startSurah: 41,  startVerse: 47,  endSurah: 45,  endVerse: 37,  totalVerses: 246 },
  { number: 26, arabicName: "حم",                 startSurah: 46,  startVerse: 1,   endSurah: 51,  endVerse: 30,  totalVerses: 242 },
  { number: 27, arabicName: "قَالَ فَمَا خَطْبُكُمْ", startSurah: 51, startVerse: 31, endSurah: 57, endVerse: 29, totalVerses: 304 },
  { number: 28, arabicName: "قَدْ سَمِعَ اللَّهُ", startSurah: 58, startVerse: 1,  endSurah: 66,  endVerse: 12,  totalVerses: 137 },
  { number: 29, arabicName: "تَبَارَكَ الَّذِي",  startSurah: 67,  startVerse: 1,   endSurah: 77,  endVerse: 50,  totalVerses: 431 },
  { number: 30, arabicName: "عَمَّ",              startSurah: 78,  startVerse: 1,   endSurah: 114, endVerse: 6,   totalVerses: 564 },
]

export const mockVerses: QuranVerse[] = [
  {
    id: "1-1",
    surahNumber: 1,
    verseNumber: 1,
    arabicText: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    swahiliTranslation: "Kwa jina la Mwenyezi Mungu Mwingi wa Rehema Mwenye Kurehemu",
    tafsir: "Aya hii inaonyesha umuhimu wa kuanza kila jambo kwa jina la Allah.",
    moral: "Tunajifunza kuanza kila kazi, ndogo au kubwa, kwa kumtaja Allah - hii inatuletea baraka na nia njema.",
  },
  {
    id: "1-2",
    surahNumber: 1,
    verseNumber: 2,
    arabicText: "الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ",
    swahiliTranslation: "Sifa njema zote ni za Mwenyezi Mungu, Mola Mlezi wa walimwengu wote",
    tafsir: "Tunampongeza Allah kwa neema zake zote.",
    moral: "Shukrani kwa Allah inapaswa kuwa tabia yetu ya kila siku, kwa kila neema tunayopokea, kubwa au ndogo.",
  },
]

export const mockHadiths: Hadith[] = [
  {
    id: "hadith-1",
    arabicText: "إِنَّمَا الأَعْمَالُ بِالنِّيَّاتِ",
    swahiliTranslation: "Hakika matendo yanategemea nia",
    narrator: "Umar bin Al-Khattab",
    source: "Sahih Bukhari",
    category: "Imani",
    date: new Date().toISOString(),
  },
  {
    id: "hadith-2",
    arabicText: "خَيْرُكُمْ مَنْ تَعَلَّمَ الْقُرْآنَ وَعَلَّمَهُ",
    swahiliTranslation: "Bora wenu ni yule anayejifunza Qurani na kuyafundisha",
    narrator: "Uthman bin Affan",
    source: "Sahih Bukhari",
    category: "Elimu",
    date: new Date().toISOString(),
  },
]

export const mockArticles: Article[] = [
  {
    id: "article-1",
    title: "Umuhimu wa Sala katika Uislamu",
    content: "Sala ni nguzo ya pili ya Uislamu na ni wajibu wa kila Muislamu aliyebaleghe...",
    category: "Ibada",
    author: "Sheikh Ahmed",
    publishedDate: new Date().toISOString(),
    imageUrl: "/islamic-prayer.png",
  },
  {
    id: "article-2",
    title: "Adabu za Kusoma Qurani",
    content: "Qurani ni neno la Mwenyezi Mungu na linahitaji heshima na adabu maalum...",
    category: "Qurani",
    author: "Ustadh Fatima",
    publishedDate: new Date().toISOString(),
    imageUrl: "/person-reading-quran.png",
  },
]

export const mockDuas: Dua[] = [
  {
    id: "dua-1",
    arabicText: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    swahiliTranslation: "Kwa jina la Mwenyezi Mungu Mwingi wa Rehema Mwenye Kurehemu",
    transliteration: "Bismillahir Rahmanir Rahim",
    category: "Kuanza Jambo",
    occasion: "Kabla ya kufanya jambo lolote",
    reference: "Qurani",
  },
  {
    id: "dua-2",
    arabicText: "الْحَمْدُ لِلَّهِ",
    swahiliTranslation: "Sifa njema zote ni za Mwenyezi Mungu",
    transliteration: "Alhamdulillah",
    category: "Shukrani",
    occasion: "Baada ya kula, kunywa, au kupata neema",
    reference: "Qurani",
  },
  {
    id: "dua-3",
    arabicText: "اللَّهُمَّ إِنِّي أَسْأَلُكَ الْعَافِيَةَ فِي الدُّنْيَا وَالْآخِرَةِ",
    swahiliTranslation: "Ee Mwenyezi Mungu, nakuomba afya duniani na akhera",
    transliteration: "Allahumma inni as'alukal afiyata fid-dunya wal-akhirah",
    category: "Afya",
    occasion: "Dua ya kila siku",
    reference: "Sunan Abu Dawud",
  },
  {
    id: "dua-4",
    arabicText: "رَبِّ اشْرَحْ لِي صَدْرِي وَيَسِّرْ لِي أَمْرِي",
    swahiliTranslation: "Mola wangu, nipanue kifua changu na unirahisishie mambo yangu",
    transliteration: "Rabbish rahli sadri wa yassir li amri",
    category: "Elimu",
    occasion: "Kabla ya kusoma au kujifunza",
    reference: "Qurani - Surah Taha",
  },
  {
    id: "dua-5",
    arabicText: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ",
    swahiliTranslation: "Ee Mwenyezi Mungu, nakukimbilia kutoka kwa wasiwasi na huzuni",
    transliteration: "Allahumma inni a'udhu bika minal-hammi wal-hazan",
    category: "Faraja",
    occasion: "Wakati wa wasiwasi au huzuni",
    reference: "Sahih Bukhari",
  },
]

// ── Adhkar ────────────────────────────────────────────────────────────────────
export const mockAdhkar: Adhkar[] = [
  // ASUBUHI (Morning) — slots 1-5
  {
    id: "adhkar-asubuhi-1",
    arabicText: "أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ",
    swahiliTranslation: "Tumeamka asubuhi na ufalme ni wa Mwenyezi Mungu, na sifa njema zote ni za Mwenyezi Mungu, hakuna Mungu isipokuwa Mwenyezi Mungu peke yake hana mshirika",
    transliteration: "Aṣbaḥnā wa aṣbaḥal mulku lillāh, wal-ḥamdu lillāh, lā ilāha illallāhu waḥdahu lā sharīka lah",
    count: 1,
    benefit: "Ikiwa mtu atasema dua hii asubuhi, atakuwa amelipwa kwa siku yake yote",
    reference: "Sahih Muslim 2723",
    slot: "asubuhi",
    order: 1,
  },
  {
    id: "adhkar-asubuhi-2",
    arabicText: "اللَّهُمَّ بِكَ أَصْبَحْنَا، وَبِكَ أَمْسَيْنَا، وَبِكَ نَحْيَا، وَبِكَ نَمُوتُ، وَإِلَيْكَ النُّشُورُ",
    swahiliTranslation: "Ee Mwenyezi Mungu, kwa msaada wako tumeamka asubuhi, na kwa msaada wako tunaendelea jioni, na kwa msaada wako tunaishi, na kwa msaada wako tunakufa, na kwako ndiko marejeo",
    transliteration: "Allāhumma bika aṣbaḥnā, wa bika amsaynā, wa bika naḥyā, wa bika namūtu, wa ilaykan-nushūr",
    count: 1,
    benefit: "Dua hii inafundisha kumtegemea Mwenyezi Mungu katika kila jambo",
    reference: "Sunan Abu Dawud 5068",
    slot: "asubuhi",
    order: 2,
  },
  {
    id: "adhkar-asubuhi-3",
    arabicText: "سُبْحَانَ اللَّهِ وَبِحَمْدِهِ",
    swahiliTranslation: "Mwenyezi Mungu ametakasika na sifa ni zake",
    transliteration: "Subḥānallāhi wa biḥamdih",
    count: 100,
    benefit: "Atakayesema maneno haya mara 100 asubuhi, madhambi yake yatasamehewa hata kama ni kama povu la bahari",
    reference: "Sahih Bukhari 6405",
    slot: "asubuhi",
    order: 3,
  },
  {
    id: "adhkar-asubuhi-4",
    arabicText: "أَعُوذُ بِاللَّهِ مِنَ الشَّيْطَانِ الرَّجِيمِ — اللَّهُ لَا إِلَهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ",
    swahiliTranslation: "Ninakimbilia kwa Mwenyezi Mungu kutoka kwa Shetani aliyelaaniwa — Mwenyezi Mungu, hakuna Mungu ila Yeye, Mwenye uhai wa milele, Msimamizi wa mambo yote",
    transliteration: "A'ūdhu billāhi minash-shayṭānir-rajīm — Allāhu lā ilāha illā huwal-ḥayyul-qayyūm",
    count: 1,
    benefit: "Kusoma Ayatul Kursi asubuhi kumpe msomaji ulinzi wa Mwenyezi Mungu hadi jioni",
    reference: "Al-Baqarah 2:255 — Sahih Bukhari",
    slot: "asubuhi",
    order: 4,
  },
  {
    id: "adhkar-asubuhi-5",
    arabicText: "اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَهَ إِلَّا أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ",
    swahiliTranslation: "Ee Mwenyezi Mungu, Wewe ni Mola wangu, hakuna Mungu isipokuwa Wewe, Uliniumba nami ni mja Wako",
    transliteration: "Allāhumma anta rabbī lā ilāha illā ant, khalaqtanī wa ana 'abduk",
    count: 1,
    benefit: "Hii ni Sayyidul Istighfar - bwana wa istighfar. Atakayesema asubuhi na kufa siku hiyo ataingia Peponi",
    reference: "Sahih Bukhari 6306",
    slot: "asubuhi",
    order: 5,
  },
  // JIONI (Evening) — slots 1-5
  {
    id: "adhkar-jioni-1",
    arabicText: "أَمْسَيْنَا وَأَمْسَى الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ",
    swahiliTranslation: "Tumefikia jioni na ufalme ni wa Mwenyezi Mungu, na sifa njema zote ni za Mwenyezi Mungu, hakuna Mungu isipokuwa Mwenyezi Mungu peke yake hana mshirika",
    transliteration: "Amsaynā wa amsal mulku lillāh, wal-ḥamdu lillāh, lā ilāha illallāhu waḥdahu lā sharīka lah",
    count: 1,
    benefit: "Sawa na adhkar ya asubuhi lakini inasomwa jioni kabla ya machweo ya jua",
    reference: "Sahih Muslim 2723",
    slot: "jioni",
    order: 1,
  },
  {
    id: "adhkar-jioni-2",
    arabicText: "اللَّهُمَّ بِكَ أَمْسَيْنَا، وَبِكَ أَصْبَحْنَا، وَبِكَ نَحْيَا، وَبِكَ نَمُوتُ، وَإِلَيْكَ الْمَصِيرُ",
    swahiliTranslation: "Ee Mwenyezi Mungu, kwa msaada wako tunaendelea jioni, na kwa msaada wako tumeamka asubuhi, na kwa msaada wako tunaishi, na kwa msaada wako tunakufa, na kwako ndiko mwisho",
    transliteration: "Allāhumma bika amsaynā, wa bika aṣbaḥnā, wa bika naḥyā, wa bika namūtu, wa ilaykal-maṣīr",
    count: 1,
    benefit: "Dua hii inafundisha kuwa maisha yote yanategemea idhini ya Mwenyezi Mungu",
    reference: "Sunan Abu Dawud 5068",
    slot: "jioni",
    order: 2,
  },
  {
    id: "adhkar-jioni-3",
    arabicText: "أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ",
    swahiliTranslation: "Ninakimbilia kwa maneno kamili ya Mwenyezi Mungu kutoka shari ya alichoviumba",
    transliteration: "A'ūdhu bikalimātillāhit-tāmmāti min sharri mā khalaq",
    count: 3,
    benefit: "Atakayesema maneno haya mara 3 jioni, hakuna sumu wala nge itakayomdhuru usiku huo",
    reference: "Sahih Muslim 2709",
    slot: "jioni",
    order: 3,
  },
  {
    id: "adhkar-jioni-4",
    arabicText: "اللَّهُمَّ إِنِّي أَسْأَلُكَ الْعَفْوَ وَالْعَافِيَةَ فِي الدُّنْيَا وَالْآخِرَةِ",
    swahiliTranslation: "Ee Mwenyezi Mungu, nakuomba msamaha na afya duniani na akhera",
    transliteration: "Allāhumma innī as'alukal-'afwa wal-'āfiyata fid-dunyā wal-ākhirah",
    count: 1,
    benefit: "Dua hii ni miongoni mwa dua bora zaidi zilizofundishwa na Mtume (S.A.W)",
    reference: "Sunan Ibn Majah 3871",
    slot: "jioni",
    order: 4,
  },
  {
    id: "adhkar-jioni-5",
    arabicText: "بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ وَهُوَ السَّمِيعُ الْعَلِيمُ",
    swahiliTranslation: "Kwa jina la Mwenyezi Mungu ambaye kwa jina lake hakuna kitu kinachoweza kudhuru ardhini wala mbinguni, naye ni Mwenye kusikia, Mwenye kujua",
    transliteration: "Bismillāhil-ladhī lā yaḍurru ma'asmihi shay'un fil-arḍi wa lā fis-samā'i wa huwas-samī'ul-'alīm",
    count: 3,
    benefit: "Atakayesema maneno haya mara 3 jioni, hatalipwa madhara yoyote hadi asubuhi",
    reference: "Sunan Abu Dawud 5088",
    slot: "jioni",
    order: 5,
  },
]

// ── Books ─────────────────────────────────────────────────────────────────────
export const mockBooks: Book[] = [
  {
    id: "book-1",
    title: "Riyadh as-Salihin",
    author: "Imam An-Nawawi",
    description: "Mkusanyiko wa hadithi sahihi kuhusu adabu na mwenendo wa Kiislamu, uliokusanywa na Imam An-Nawawi. Kitabu hiki ni moja ya vitabu vya hadithi vinavyosomwa sana duniani kote.",
    category: "Hadith",
    language: "Kiswahili",
    coverUrl: "/morning-adhkar.jpg",
    totalPages: 412,
    publishedYear: "2020",
    downloadCount: 1240,
    addedDate: new Date().toISOString(),
    isAvailable: true,
  },
  {
    id: "book-2",
    title: "Fiqh ya Ibada",
    author: "Sheikh Said Musa",
    description: "Kitabu hiki kinaelezea kwa kina sheria za ibada za Kiislamu ikiwemo sala, swaum, zaka na hija. Kimeandikwa kwa lugha ya Kiswahili inayoeleweka.",
    category: "Fiqh",
    language: "Kiswahili",
    coverUrl: "/evening-adhkar.jpg",
    totalPages: 280,
    publishedYear: "2019",
    downloadCount: 890,
    addedDate: new Date().toISOString(),
    isAvailable: true,
  },
  {
    id: "book-3",
    title: "Tafsiri ya Qur'ani Tukufu",
    author: "Sheikh Abdullah Saleh",
    description: "Tafsiri kamili ya Qur'ani Tukufu kwa Kiswahili, ikielezea maana na hukumu zilizomo katika kila aya. Imeandikwa kwa usahihi wa hali ya juu.",
    category: "Tafsiri",
    language: "Kiswahili",
    coverUrl: "/quranic-duas.jpg",
    totalPages: 1250,
    publishedYear: "2021",
    downloadCount: 2100,
    addedDate: new Date().toISOString(),
    isAvailable: true,
  },
  {
    id: "book-4",
    title: "Usul wa Dini ya Kiislamu",
    author: "Dr. Amina Hassan",
    description: "Utangulizi wa kina kuhusu misingi ya Uislamu, ikiwemo imani, ibada na mwenendo wa Kiislamu. Kitabu kinafaa kwa wanafunzi wote wa elimu ya Dini.",
    category: "Akida",
    language: "Kiswahili",
    coverUrl: "/sunnah-duas.jpg",
    totalPages: 196,
    publishedYear: "2022",
    downloadCount: 654,
    addedDate: new Date().toISOString(),
    isAvailable: true,
  },
]

// ── Helper function to get daily hadith
export function getDailyHadith(): Hadith {
  const dayOfYear = Math.floor((Date.now() - new Date(new Date().getFullYear(), 0, 0).getTime()) / 86400000)
  return mockHadiths[dayOfYear % mockHadiths.length]
}

export function getDailyDua(): Dua {
  const dayOfYear = Math.floor((Date.now() - new Date(new Date().getFullYear(), 0, 0).getTime()) / 86400000)
  return mockDuas[dayOfYear % mockDuas.length]
}

export function getAdhkarBySlot(slot: "asubuhi" | "jioni"): Adhkar[] {
  return mockAdhkar.filter((a) => a.slot === slot).sort((a, b) => a.order - b.order)
}

export function getCurrentSlot(): "asubuhi" | "jioni" {
  const hour = new Date().getHours()
  return hour >= 5 && hour < 12 ? "asubuhi" : "jioni"
}
